// Activity Room actions
const GET_ACTIVITY_ROOM_DETAINEES = 'app/ActivityRoom/GET_ACTIVITY_ROOM_DETAINEES';
const GET_ACTIVITY_ROOM_DETAINEES_SUCCESS = 'app/ActivityRoom/GET_ACTIVITY_ROOM_DETAINEES_SUCCESS';

export default {
  GET_ACTIVITY_ROOM_DETAINEES,
  GET_ACTIVITY_ROOM_DETAINEES_SUCCESS,
};
