// Activity Room actions
const GET_ACTIVITY_ROOM_DETAINEES = 'app/ActivityRoom/GET_ACTIVITY_ROOM_DETAINEES';
const GET_ACTIVITY_ROOM_DETAINEES_SUCCESS = 'app/ActivityRoom/GET_ACTIVITY_ROOM_DETAINEES_SUCCESS';
const CHECK_IN = 'app/ActivityRoom/CHECK_IN';
const CHECK_IN_SUCCESS = 'app/ActivityRoom/CHECK_IN_SUCCESS';
const CHECK_IN_FAIL = 'app/ActivityRoom/CHECK_IN_FAIL';

export default {
  GET_ACTIVITY_ROOM_DETAINEES,
  GET_ACTIVITY_ROOM_DETAINEES_SUCCESS,
  CHECK_IN,
  CHECK_IN_SUCCESS,
  CHECK_IN_FAIL,
};
