const GET_DETAINEE_PROFILE_SUCCESS = 'DMU/detaineeProfile/GET_DETAINEE_PROFILE_SUCCESS';
const GET_DETAINEE_PROFILE_FAILURE = 'DMU/detaineeProfile/GET_DETAINEE_PROFILE_FAILURE';

const GET_AVAILABLE_ROOMS_SUCCESS = 'DMU/detaineeProfile/GET_AVAILABLE_ROOMS_SUCCESS';
const GET_AVAILABLE_ROOMS_FAILURE = 'DMU/detaineeProfile/GET_AVAILABLE_ROOMS_FAILURE';

const UPDATE_ACTIVITY_ROOM_STATUS_FAILURE = 'DMU/detaineeProfile/UPDATE_ACTIVITY_ROOM_STATUS_FAILURE';
const GET_LATEST_TEMP_ABS_FAILURE = 'DMU/detaineeProfile/GET_LATEST_TEMP_ABS_FAILURE';
const UPDATE_LATEST_TEMP_ABS_FAILURE = 'DMU/detaineeProfile/UPDATE_LATEST_TEMP_ABS_FAILURE';

const SAVE_DETENTION_LOG_SUCCESS = 'DMU/detaineeProfile/SAVE_DETENTION_LOG_SUCCESS';
const SAVE_DETENTION_LOG_FAILURE = 'DMU/detaineeProfile/SAVE_DETENTION_LOG_FAILURE';

const SAVE_TEMPORARY_ABSENCE_SUCCESS = 'DMU/detaineeProfile/SAVE_TEMPORARY_ABSENCE_SUCCESS';
const SAVE_TEMPORARY_ABSENCE_FAILURE = 'DMU/detaineeProfile/SAVE_TEMPORARY_ABSENCE_FAILURE';

const UPDATE_BAIL_HEARING_COUNT = 'DMU/detaineeProfile/UPDATE_BAIL_HEARING_COUNT';
const UPDATE_PHONE_ACCEPTED_COUNT = 'DMU/detaineeProfile/UPDATE_PHONE_ACCEPTED_COUNT';
const UPDATE_PHONE_DECLINED_COUNT = 'DMU/detaineeProfile/UPDATE_PHONE_DECLINED_COUNT';
const UPDATE_MEDICAL_COUNT = 'DMU/detaineeProfile/UPDATE_MEDICAL_COUNT';
const UPDATE_FINGERPRINTING_COUNT = 'DMU/detaineeProfile/UPDATE_FINGERPRINTING_COUNT';
const UPDATE_BREATH_TEST_COUNT = 'DMU/detaineeProfile/UPDATE_BREATH_TEST_COUNT';
const UPDATE_INTERVIEW_COUNT = 'DMU/detaineeProfile/UPDATE_INTERVIEW_COUNT';

export default {
  GET_DETAINEE_PROFILE_SUCCESS,
  GET_DETAINEE_PROFILE_FAILURE,
  GET_AVAILABLE_ROOMS_SUCCESS,
  GET_AVAILABLE_ROOMS_FAILURE,
  UPDATE_ACTIVITY_ROOM_STATUS_FAILURE,
  GET_LATEST_TEMP_ABS_FAILURE,
  UPDATE_LATEST_TEMP_ABS_FAILURE,
  SAVE_DETENTION_LOG_SUCCESS,
  SAVE_DETENTION_LOG_FAILURE,
  SAVE_TEMPORARY_ABSENCE_SUCCESS,
  SAVE_TEMPORARY_ABSENCE_FAILURE,
  UPDATE_BAIL_HEARING_COUNT,
  UPDATE_PHONE_ACCEPTED_COUNT,
  UPDATE_PHONE_DECLINED_COUNT,
  UPDATE_MEDICAL_COUNT,
  UPDATE_FINGERPRINTING_COUNT,
  UPDATE_BREATH_TEST_COUNT,
  UPDATE_INTERVIEW_COUNT,
};
