const START_SIGN_IN = 'app/Cells/START_SIGN_IN';
const START_AUTHENTICATE = 'app/Cells/START_AUTHENTICATE';
const AUTHENTICATE_SUCCESS = 'app/Cells/AUTHENTICATE_SUCCESS';
const AUTHENTICATE_FAIL = 'app/Cells/AUTHENTICATE_FAIL';
const CANCEL_AUTHENTICATE = 'app/Cells/CANCEL_AUTHENTICATE';
const LOG_OUT = 'app/Cells/LOG_OUT';

export default {
  START_SIGN_IN,
  START_AUTHENTICATE,
  AUTHENTICATE_SUCCESS,
  AUTHENTICATE_FAIL,
  CANCEL_AUTHENTICATE,
  LOG_OUT,
};
