// Cell actions
const GET_CELL_DETAILS_SUCCESS = 'app/Cells/GET_CELL_DETAILS_SUCCESS';
const GET_CELL_DETAINEES_SUCCESS = 'app/Cells/GET_CELL_DETAINEES_SUCCESS';
const GET_CELL_DETAINEES = 'app/Cells/GET_CELL_DETAINEES';

// Cell-check actions
const VISUAL_CHECK = 'app/Cells/VISUAL_CHECK';
const VERBAL_CHECK = 'app/Cells/VERBAL_CHECK';

export default {
  GET_CELL_DETAILS_SUCCESS,
  GET_CELL_DETAINEES_SUCCESS,
  GET_CELL_DETAINEES,
  VISUAL_CHECK,
  VERBAL_CHECK,
};
