// Cell actions
const GET_CELL_DETAILS_SUCCESS = 'app/Cells/GET_CELL_DETAILS_SUCCESS';
const GET_CELL_DETAINEES_SUCCESS = 'app/Cells/GET_CELL_DETAINEES_SUCCESS';
const GET_CELL_DETAINEES = 'app/Cells/GET_CELL_DETAINEES';

// Cell-check actions
const VISUAL_CHECK = 'app/Cells/VISUAL_CHECK';
const VERBAL_CHECK = 'app/Cells/VERBAL_CHECK';
const SAVE_CELL_CHECK = 'app/Cells/SAVE_CELL_CHECK';
const SAVE_CELL_CHECK_SUCCESS = 'app/Cells/SAVE_CELL_CHECK_SUCCESS';

// Meal-provision actions
const ACCEPT_MEAL = 'app/Cells/ACCEPT_MEAL';
const REJECT_MEAL = 'app/Cells/REJECT_MEAL';
const NOT_APPLICABLE_MEAL = 'app/Cells/NOT_APPLICABLE_MEAL';
const SAVE_MEAL = 'app/Cells/SAVE_MEAL';
const SAVE_MEAL_SUCCESS = 'app/Cells/SAVE_MEAL_SUCCESS';

export default {
  GET_CELL_DETAILS_SUCCESS,
  GET_CELL_DETAINEES_SUCCESS,
  GET_CELL_DETAINEES,
  VISUAL_CHECK,
  VERBAL_CHECK,
  SAVE_CELL_CHECK,
  SAVE_CELL_CHECK_SUCCESS,
  ACCEPT_MEAL,
  REJECT_MEAL,
  NOT_APPLICABLE_MEAL,
  SAVE_MEAL,
  SAVE_MEAL_SUCCESS,
};
