// Cell actions
const GET_CELL_DETAILS_SUCCESS = 'app/Cells/GET_CELL_DETAILS_SUCCESS';
const GET_CELL_DETAINEES_SUCCESS = 'app/Cells/GET_CELL_DETAINEES_SUCCESS';

export default {
  GET_CELL_DETAILS_SUCCESS,
  GET_CELL_DETAINEES_SUCCESS,
};
