// DMU Service URLS
const CELL_URL = 'api/cells/';
const DETENTION_LOGS_URL = 'api/detention-logs/';

// Detention Log Data Types
const DETENTION_LOG_DATA_TYPE_MEAL = 'IsMeal';
const DETENTION_LOG_DATA_TYPE_MEDICATION = 'IsMedication';
const DETENTION_LOG_DATA_TYPE_CELL_CHECK = 'IsCellCheck';
const DETENTION_LOG_DATA_TYPE_DETAINEE_ACTION = 'DetaineeAction';

// Detention Log Action Types
const DETENTION_LOG_ACTION_TYPE_ACCEPT = 'Accept';
const DETENTION_LOG_ACTION_TYPE_REJECT = 'Reject';
const DETENTION_LOG_ACTION_TYPE_NOT_APPLICABLE = 'NotApplicable';
const DETENTION_LOG_ACTION_TYPE_VISUAL = 'Visual';
const DETENTION_LOG_ACTION_TYPE_VERBAL = 'Verbal';
const DETENTION_LOG_ACTION_TYPE_PHONE_DECLINED = 'PhoneDeclined';

export default {
  CELL_URL,
  DETENTION_LOGS_URL,
  DETENTION_LOG_DATA_TYPE_MEAL,
  DETENTION_LOG_DATA_TYPE_MEDICATION,
  DETENTION_LOG_DATA_TYPE_CELL_CHECK,
  DETENTION_LOG_DATA_TYPE_DETAINEE_ACTION,
  DETENTION_LOG_ACTION_TYPE_ACCEPT,
  DETENTION_LOG_ACTION_TYPE_REJECT,
  DETENTION_LOG_ACTION_TYPE_NOT_APPLICABLE,
  DETENTION_LOG_ACTION_TYPE_VISUAL,
  DETENTION_LOG_ACTION_TYPE_VERBAL,
  DETENTION_LOG_ACTION_TYPE_PHONE_DECLINED,
};
