const READ_SCANNED_CARD = "dmu/sessionManagement/READ_SCANNED_CARD";
const USER_AUTHENTICATION_SUCCESS = "dmu/sessionManagement/AUTHENTICATION_SUCCESS";
const USER_AUTHENTICATION_FAILURE = "dmu/sessionManagement/AUTHENTICATION_FAILURE";
const USER_LOGOUT = "dmu/sessionManagement/LOGOUT";
const RESET_LOGOUT_REDIRECT = "dmu/sessionManagement/RESET_LOGOUT_REDIRECT";

export default {
  READ_SCANNED_CARD,
  USER_AUTHENTICATION_SUCCESS,
  USER_AUTHENTICATION_FAILURE,
  USER_LOGOUT,
  RESET_LOGOUT_REDIRECT
}