const READ_SCANNED_CARD = 'DMU/SessionManagement/READ_SCANNED_CARD';
const USER_AUTHENTICATION_SUCCESS = 'DMU/SessionManagement/AUTHENTICATION_SUCCESS';
const USER_AUTHENTICATION_FAILURE = 'DMU/SessionManagement/AUTHENTICATION_FAILURE';
const USER_LOGOUT = 'DMU/SessionManagement/LOGOUT';
const RESET_LOGOUT_REDIRECT = 'DMU/SessionManagement/RESET_LOGOUT_REDIRECT';

export default {
  READ_SCANNED_CARD,
  USER_AUTHENTICATION_SUCCESS,
  USER_AUTHENTICATION_FAILURE,
  USER_LOGOUT,
  RESET_LOGOUT_REDIRECT,
};
