const SET_ISMEAL = 'DMU/WelfareManagement/SET_ISMEAL';
const SET_ISMEDICATION = 'DMU/WelfareManagement/SET_ISMEDICATION';
const SET_ISCELLCHECK = 'DMU/WelfareManagement/SET_ISCELLCHECK';
const RESET_CELL_WELFARE = 'DMU/WelfareManagement/RESET_CELL_WELFARE';

const CREATE_DETAINEE_WELFARE_DATA = 'DMU/WelfareManagement/CREATE_DETAINEE_WELFARE_DATA';
const EDIT_DETAINEE_WELFARE_DATA = 'DMU/WelfareManagement/EDIT_DETAINEE_WELFARE_DATA';
const DELETE_DETAINEE_WELFARE_DATA = 'DMU/WelfareManagement/DELETE_DETAINEE_WELFARE_DATA';
const DELETE_CELL_WELFARE_DATA = 'DMU/WelfareManagement/DELETE_CELL_WELFARE_DATA';

export default {
  SET_ISMEAL,
  SET_ISMEDICATION,
  SET_ISCELLCHECK,
  RESET_CELL_WELFARE,

  CREATE_DETAINEE_WELFARE_DATA,
  EDIT_DETAINEE_WELFARE_DATA,
  DELETE_DETAINEE_WELFARE_DATA,
  DELETE_CELL_WELFARE_DATA,
};
