const SET_ISMEAL = "dmu/welfareManagement/SET_ISMEAL";
const SET_ISMEDICATION = "dmu/welfareManagement/SET_ISMEDICATION";
const SET_ISCELLCHECK = "dmu/welfareManagement/SET_ISCELLCHECK";
const RESET_CELL_WELFARE = "dmu/welfareManagement/RESET_CELL_WELFARE";

const CREATE_DETAINEE_WELFARE_DATA = "dmu/welfareManagement/CREATE_DETAINEE_WELFARE_DATA";
const EDIT_DETAINEE_WELFARE_DATA = "dmu/welfareManagement/EDIT_DETAINEE_WELFARE_DATA";
const DELETE_DETAINEE_WELFARE_DATA = "dmu/welfareManagement/DELETE_DETAINEE_WELFARE_DATA";
const DELETE_CELL_WELFARE_DATA = "dmu/welfareManagement/DELETE_CELL_WELFARE_DATA";

export default {
  SET_ISMEAL,
  SET_ISMEDICATION,
  SET_ISCELLCHECK,
  RESET_CELL_WELFARE,

  CREATE_DETAINEE_WELFARE_DATA,
  EDIT_DETAINEE_WELFARE_DATA,
  DELETE_DETAINEE_WELFARE_DATA,
  DELETE_CELL_WELFARE_DATA,
};