const GET_VERSIONS_SUCCESS = 'app/common/GET_VERSIONS_SUCCESS';
const REFRESH_AUTHENTICATION_TIMEOUT = 'app/common/REFRESH_AUTHENTICATION_TIMEOUT';
const START_AUTHENTICATION_TIMEOUT = 'app/common/START_AUTHENTICATION_TIMEOUT';
const STOP_AUTHENTICATION_TIMEOUT = 'app/common/STOP_AUTHENTICATION_TIMEOUT';

export default {
  GET_VERSIONS_SUCCESS,
  REFRESH_AUTHENTICATION_TIMEOUT,
  START_AUTHENTICATION_TIMEOUT,
  STOP_AUTHENTICATION_TIMEOUT,
};
