const GET_CELL_INFO_SUCCESS = "dmu/cellManagement/GET_CELL_INFO_SUCCESS";
const GET_CELL_INFO_FAILURE = "dmu/cellManagement/GET_CELL_INFO_FAILURE";

const GET_CELL_DETAINEES_SUCCESS = "dmu/cellManagement/GET_CELL_DETAINEES_SUCCESS";
const GET_CELL_DETAINEES_FAILURE = "dmu/cellManagement/GET_CELL_DETAINEES_FAILURE";

export default {
  GET_CELL_INFO_SUCCESS,
  GET_CELL_INFO_FAILURE,
  GET_CELL_DETAINEES_SUCCESS,
  GET_CELL_DETAINEES_FAILURE,
};