const GET_CELL_INFO_SUCCESS = 'DMU/CellManagement/GET_CELL_INFO_SUCCESS';
const GET_CELL_INFO_FAILURE = 'DMU/CellManagement/GET_CELL_INFO_FAILURE';

const GET_CELL_DETAINEES_SUCCESS = 'DMU/CellManagement/GET_CELL_DETAINEES_SUCCESS';
const GET_CELL_DETAINEES_FAILURE = 'DMU/CellManagement/GET_CELL_DETAINEES_FAILURE';

export default {
  GET_CELL_INFO_SUCCESS,
  GET_CELL_INFO_FAILURE,
  GET_CELL_DETAINEES_SUCCESS,
  GET_CELL_DETAINEES_FAILURE,
};
