// Detainee actions
const GET_DETAINEE = 'app/Detainee/GET_DETAINEE';
const GET_DETAINEE_SUCCESS = 'app/Detainee/GET_DETAINEE_SUCCESS';

// Activity rooms
const GET_AVAILABLE_ACTIVITY_ROOMS = 'app/Detainee/GET_AVAILABLE_ACTIVITY_ROOMS';
const GET_AVAILABLE_ACTIVITY_ROOMS_SUCCESS = 'app/Detainee/GET_AVAILABLE_ACTIVITY_ROOMS_SUCCESS';

export default {
  GET_DETAINEE,
  GET_DETAINEE_SUCCESS,
  GET_AVAILABLE_ACTIVITY_ROOMS,
  GET_AVAILABLE_ACTIVITY_ROOMS_SUCCESS,
};
