// Detainee actions
const GET_DETAINEE = 'app/Detainee/GET_DETAINEE';
const GET_DETAINEE_SUCCESS = 'app/Detainee/GET_DETAINEE_SUCCESS';

// Activity rooms
const ASSIGN_TO_ROOM = 'app/Detainee/ASSIGN_TO_ROOM';
const ASSIGN_TO_ROOM_FAILURE = 'app/Detainee/ASSIGN_TO_ROOM_FAILURE';
const ASSIGN_TO_ROOM_SUCCESS = 'app/Detainee/ASSIGN_TO_ROOM_SUCCESS';
const GET_AVAILABLE_ACTIVITY_ROOMS = 'app/Detainee/GET_AVAILABLE_ACTIVITY_ROOMS';
const GET_AVAILABLE_ACTIVITY_ROOMS_SUCCESS = 'app/Detainee/GET_AVAILABLE_ACTIVITY_ROOMS_SUCCESS';

export default {
  ASSIGN_TO_ROOM,
  ASSIGN_TO_ROOM_FAILURE,
  ASSIGN_TO_ROOM_SUCCESS,
  GET_DETAINEE,
  GET_DETAINEE_SUCCESS,
  GET_AVAILABLE_ACTIVITY_ROOMS,
  GET_AVAILABLE_ACTIVITY_ROOMS_SUCCESS,
};
