// Detainee actions
const GET_DETAINEE = 'app/Detainee/GET_DETAINEE';
const GET_DETAINEE_SUCCESS = 'app/Detainee/GET_DETAINEE_SUCCESS';

// Activity rooms
const ASSIGN_TO_ROOM = 'app/Detainee/ASSIGN_TO_ROOM';
const ASSIGN_TO_ROOM_FAILURE = 'app/Detainee/ASSIGN_TO_ROOM_FAILURE';
const ASSIGN_TO_ROOM_SUCCESS = 'app/Detainee/ASSIGN_TO_ROOM_SUCCESS';
const DECLINE_PHONECALL = 'app/Detainee/DECLINE_PHONECALL';
const DECLINE_PHONECALL_FAILURE = 'app/Detainee/DECLINE_PHONECALL_FAILURE';
const DECLINE_PHONECALL_SUCCESS = 'app/Detainee/DECLINE_PHONECALL_SUCCESS';
const GET_AVAILABLE_ACTIVITY_ROOMS = 'app/Detainee/GET_AVAILABLE_ACTIVITY_ROOMS';
const GET_AVAILABLE_ACTIVITY_ROOMS_REFRESH = 'app/Detainee/GET_AVAILABLE_ACTIVITY_ROOMS_REFRESH';
const GET_AVAILABLE_ACTIVITY_ROOMS_SUCCESS = 'app/Detainee/GET_AVAILABLE_ACTIVITY_ROOMS_SUCCESS';

export default {
  ASSIGN_TO_ROOM,
  ASSIGN_TO_ROOM_FAILURE,
  ASSIGN_TO_ROOM_SUCCESS,
  DECLINE_PHONECALL,
  DECLINE_PHONECALL_FAILURE,
  DECLINE_PHONECALL_SUCCESS,
  GET_DETAINEE,
  GET_DETAINEE_SUCCESS,
  GET_AVAILABLE_ACTIVITY_ROOMS,
  GET_AVAILABLE_ACTIVITY_ROOMS_REFRESH,
  GET_AVAILABLE_ACTIVITY_ROOMS_SUCCESS,
};
